allocation_constraints:
  fully_invested: true
  max_tickers: 5
invest_quarter: 2024Q4
output_dir: results/industry_js_100/finance
tickers:
  - BLK
  - GS
  - JPM
  - MS
use_cash_virtual_ticker: true
