allocation_constraints:
  fully_invested: true
  max_tickers: 13
invest_quarter: 2021Q4
output_dir: results/baseline_sweep/rand13/a3b3fed8
tickers:
- AMD
- AMZN
- BAC
- CAT
- COST
- CVX
- JPM
- MS
- NKE
- PG
- TSLA
- UNH
- XOM
use_cash_virtual_ticker: true
