allocation_constraints:
  fully_invested: true
  max_tickers: 4
invest_quarter: 2023Q2
output_dir: results/baseline_sweep/financials/bebbfc49
tickers:
- BAC
- GS
- JPM
- MS
use_cash_virtual_ticker: true
