allocation_constraints:
  fully_invested: true
  max_tickers: 19
invest_quarter: 2023Q4
output_dir: results/baseline_sweep
tickers:
- AAPL
- AMD
- AMZN
- BAC
- CAT
- COP
- COST
- CVX
- GS
- JPM
- MSFT
- NKE
- NVDA
- PG
- RTX
- TSLA
- UNH
- WMT
- XOM
use_cash_virtual_ticker: true
