allocation_constraints:
  fully_invested: true
  max_tickers: 8
invest_quarter: 2022Q2
output_dir: results/baseline_sweep/rand8/4521244b
tickers:
- AMD
- BAC
- DAL
- JNJ
- JPM
- MSFT
- OXY
- RTX
use_cash_virtual_ticker: true
