allocation_constraints:
  fully_invested: true
  max_tickers: 8
invest_quarter: 2022Q2
output_dir: results/baseline_sweep/rand8/5195513f
tickers:
- AMZN
- BAC
- CAT
- COST
- DAL
- GS
- JPM
- RTX
use_cash_virtual_ticker: true
