allocation_constraints:
  fully_invested: true
  max_tickers: 13
invest_quarter: 2023Q2
output_dir: results/baseline_sweep/rand13/2e482b24
tickers:
- AAPL
- AMD
- AMZN
- CAT
- COP
- GS
- JPM
- MSFT
- NKE
- NVDA
- PG
- SLB
- UNH
use_cash_virtual_ticker: true
