allocation_constraints:
  fully_invested: true
  max_tickers: 9
invest_quarter: 2023Q1
output_dir: results/baseline_sweep/rand9/2aba5c03
tickers:
- AAPL
- AMD
- CVX
- GS
- JPM
- NKE
- SLB
- TSLA
- WMT
use_cash_virtual_ticker: true
