allocation_constraints:
  fully_invested: true
  max_tickers: 6
invest_quarter: 2022Q1
output_dir: results/baseline_sweep/rand6/9893fff7
tickers:
- AAPL
- COP
- DE
- MSFT
- NKE
- UNH
use_cash_virtual_ticker: true
