allocation_constraints:
  fully_invested: true
  max_tickers: 7
invest_quarter: 2022Q1
output_dir: results/baseline_sweep/rand7/123a695b
tickers:
- AMD
- BAC
- CVX
- DE
- JNJ
- MS
- TSLA
use_cash_virtual_ticker: true
