allocation_constraints:
  fully_invested: true
  max_tickers: 21
invest_quarter: 2022Q1
tickers:
- AAPL
- AMD
- AMZN
- BAC
- CAT
- COP
- COST
- CVX
- DE
- GS
- JNJ
- JPM
- MS
- MSFT
- NKE
- NVDA
- PG
- TSLA
- UNH
- WMT
- XOM
use_cash_virtual_ticker: true
