allocation_constraints:
  fully_invested: true
  max_tickers: 6
invest_quarter: 2022Q1
output_dir: results/baseline_sweep/rand6/759dab56
tickers:
- AAPL
- COST
- MSFT
- PG
- TSLA
- WMT
use_cash_virtual_ticker: true
