allocation_constraints:
  fully_invested: true
  max_tickers: 4
invest_quarter: 2023Q4
output_dir: results/baseline_sweep/rand4/262a9f19
tickers:
- CAT
- CVX
- NVDA
- XOM
use_cash_virtual_ticker: true
