allocation_constraints:
  fully_invested: true
  max_tickers: 12
invest_quarter: 2023Q4
output_dir: results/baseline_sweep/rand12_2
tickers:
- AAPL
- AMD
- AMZN
- CAT
- COST
- CVX
- GS
- MSFT
- NKE
- PG
- TSLA
- XOM
use_cash_virtual_ticker: true
