allocation_constraints:
  fully_invested: true
  max_tickers: 7
invest_quarter: 2023Q4
output_dir: results/baseline_sweep/rand7_2
tickers:
- BAC
- CAT
- GS
- JPM
- NKE
- TSLA
- WMT
use_cash_virtual_ticker: true
