allocation_constraints:
  fully_invested: true
  max_tickers: 7
invest_quarter: 2022Q3
output_dir: results/baseline_sweep/rand7_1
tickers:
- BAC
- COP
- GS
- JNJ
- MSFT
- NVDA
- WMT
use_cash_virtual_ticker: true
