allocation_constraints:
  fully_invested: true
  max_tickers: 13
invest_quarter: 2021Q4
output_dir: results/baseline_sweep/rand13/1ea2f33e
tickers:
- AAPL
- AMD
- BAC
- CAT
- COST
- CVX
- DE
- GS
- JNJ
- JPM
- TSLA
- UNH
- XOM
use_cash_virtual_ticker: true
