allocation_constraints:
  fully_invested: true
  max_tickers: 5
invest_quarter: 2023Q3
output_dir: results/baseline_sweep/rand5/cf3b0917
tickers:
- AMD
- CVX
- NVDA
- RTX
- SLB
use_cash_virtual_ticker: true
