allocation_constraints:
  fully_invested: true
  max_tickers: 12
invest_quarter: 2022Q1
output_dir: results/baseline_sweep/rand12_1
tickers:
- AMZN
- BAC
- COP
- COST
- CVX
- DE
- JPM
- PG
- TSLA
- UNH
- WMT
- XOM
use_cash_virtual_ticker: true
